"""
Django settings for geekgalaxy_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(!0q(67gk=x!8ny2o*5(6t_7rhp%_=+$q6q)h1k@$kx=#b#(!u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Nossos apps e bibliotecas de terceiros
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'vendas_api.apps.VendasApiConfig', # Ou 'vendas_api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Adicionar aqui
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'geekgalaxy_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geekgalaxy_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# geekgalaxy_project/settings.py - Alterado para MySQL

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'geekgalaxy_db',        # O nome do banco que você criou
        'USER': 'root',                # Seu usuário do MySQL (geralmente 'root')
        'PASSWORD': '3306',  # << COLOQUE A SUA SENHA AQUI
        'HOST': 'localhost',           # Ou '127.0.0.1'
        'PORT': '3306',                # Porta padrão do MySQL
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# geekgalaxy_project/settings.py

# ... (outras configurações) ...

# Configurações do CORS
CORS_ALLOW_ALL_ORIGINS = True # Permite todas as origens durante o desenvolvimento

# Ou, para ser mais específico (exemplo, se seu app desktop rodasse em uma porta específica):
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000", # Se o front-end rodasse em um servidor de desenvolvimento React/Vue
#     "http://127.0.0.1:3000",
#     # Para app desktop, pode não ser necessário se ele não "servir" de uma origem web.
#     # Mas para APIs acessadas localmente, CORS_ALLOW_ALL_ORIGINS = True é mais simples no início.
# ]

# geekgalaxy_project/settings.py

AUTH_USER_MODEL = 'vendas_api.Usuario'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.authentication.SessionAuthentication', # Descomente se quiser usar o login do admin para testar a API no navegador
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        # Por padrão, todas as views da API exigirão que o usuário esteja autenticado.
        # Já sobrescrevemos isso em cada ViewSet com permissões mais específicas.
        'rest_framework.permissions.IsAuthenticated',
    ]
}